name: CI Workflow Repository Dispatch
on:
  repository_dispatch:
    types: [test-event]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building the project..."
