name: CI Workflow Push
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Build
        run: |
          echo SECRET:${{ secrets.SOMETHING_SECRET }}
          echo SECRET:${{ secrets.DB_PASSWORD }}
          echo VARIABLE ENTORNO:${{ env.SOMETHING_VARAIBLE }}
          echo VARIABLE REPO:${{ vars.SOMETHING_REPO }}
          echo CONTEXT:${{ github.ref }}
