name: CI Workflow Push
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Build
        run: |
          echo SECRET:${{ secrets.SOMETHING_SECRET }}
          echo VARAIBLE:${{ variables.SOMETHING_VARAIBLE }}
