name: Workflow with Scripts
on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # run: |
        #   git init
        #   git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        #   git fetch origin ${{ github.ref }} --depth=1
        #   git checkout FETCH_HEAD
        #   ls -lha

      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14' 
      - run: python3 main.py
      # - id: step1
      #   name: Step 1
      #   run: |
      #     echo "Installing dependencies"
      #     echo "status=success" >> $GITHUB_OUTPUT
      # - id: step2
      #   name: Step 2
      #   if: ${{ steps.step1.outputs.status == 'success' }}
      #   run: |
      #     echo "El resultado del paso anterior fue ${{ steps.step1.outputs.status }}"
      #     echo "Running tests!"

          