name: Workflow with Scripts
on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        shell: python
        run: |
          print("Installing dependencies...")
          print("Running tests")
          